[project]
name = "cli-cag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cag",
]

[tool.uv.sources]
cag = { git = "https://github.com/panalexeu/cag.git" }
